import Link from 'next/link';
import {ArrowRight,ArrowUpRight,ShieldCheck,Sparkles,Headphones,Smartphone,PenTool,CheckCircle2,MessageCircle,ChevronRight} from 'lucide-react';
import {Phone} from '@/components/phone';
import {Catalog} from '@/components/catalog';
export default function Home(){return <main>
<section className="hero new-hero"><div className="container hero-grid"><div className="hero-content"><div className="hero-kicker"><span className="pulse"/> SRI LANKA • YOUR MOBILE DESTINATION</div><div className="local-pill">CHAMA MOBILE <span>✳</span> iPHONE SPECIALISTS</div><h1>Your next<br/><span>iPhone.</span><br/>Starts here.</h1><p>Discover the iPhone that fits your lifestyle. Explore standout devices, thoughtful upgrades and mobile care — all in one place.</p><div className="hero-buttons"><Link href="/shop?category=iPhone" className="btn btn-white">Explore iPhones <ArrowUpRight size={18}/></Link><Link href="/services" className="hero-secondary">Our Services <ArrowRight size={18}/></Link></div><div className="hero-micro"><div className="avatar-stack"><span>C</span><span>M</span><span>✳</span></div><div><strong>STYLE. POWER. YOUR CHOICE.</strong><small>Find your perfect fit.</small></div></div></div><div className="hero-art"><div className="hero-orbit hero-orbit-1"/><div className="hero-orbit hero-orbit-2"/><div className="hero-art-label">THE iPHONE<br/>EDIT <span>↗</span></div><div className="hero-phone-one"><Phone color="#b0a89a" size="hero" rotate={-20}/></div><div className="hero-phone-two"><Phone color="#53565b" size="hero" rotate={17}/></div><div className="hero-side-mark">PREMIUM MOBILE EXPERIENCE</div><div className="hero-art-bottom">CHAMA MOBILE <span>THE NEXT UPGRADE</span></div></div></div><div className="hero-footer container"><span>DISCOVER MORE ↓</span><span>Your phone. Your style.</span></div></section>
<section className="benefit-band"><div className="container benefit-items"><div><ShieldCheck size={23}/><span><strong>Browse with ease</strong><small>Compare models and features</small></span></div><div><Sparkles size={23}/><span><strong>Find your upgrade</strong><small>Meet your next iPhone</small></span></div><div><Headphones size={23}/><span><strong>Repairs & Support</strong><small>Ask about our services</small></span></div></div></section>
<section className="section collection-section container"><div className="section-heading"><div><span className="eyebrow"><span className="eyebrow-line"/> THE IPHONE COLLECTION</span><h2>Meet your next <em>upgrade.</em></h2><p>Browse the collection and compare models, storage and features.</p></div><Link href="/shop" className="text-link">View all phones <ArrowUpRight size={17}/></Link></div><Catalog featured limit={4}/><p className="demo-local-note">* Demo products and illustrative prices only. Please confirm current prices and availability.</p></section>
<section className="local-showcase container"><div className="local-showcase-copy"><span className="eyebrow">MORE THAN JUST PHONES</span><h2>A fresh look.<br/><em>For your phone.</em></h2><p>From screen and battery enquiries to personalisation, explore options designed around your device.</p><div className="local-feature"><CheckCircle2 size={18}/> Repair enquiries</div><div className="local-feature"><CheckCircle2 size={18}/> Custom looks and upgrades</div><div className="local-feature"><CheckCircle2 size={18}/> Find the right iPhone</div><Link className="btn btn-dark" href="/services">Explore services <ArrowUpRight size={18}/></Link></div><div className="local-showcase-art"><span className="showcase-label">MAKE IT YOURS / 02</span><div className="local-showcase-device"><Phone color="#c7d5c6" size="hero" rotate={-12}/></div><span className="showcase-sign">CM✳</span></div></section>
<section className="statement-section"><div className="container statement-inner"><span className="eyebrow">BUILT AROUND YOUR NEXT MOVE</span><h2>Your phone.<br/><em>Your signature.</em></h2><div className="statement-bottom"><p>Premium looks. Smart choices. A simpler mobile shopping experience.</p><Link href="/about" className="circle-link" aria-label="About Us"><ArrowUpRight size={30}/></Link></div><span className="statement-decoration">CM<span>✳</span></span></div></section>
<section className="section container service-preview"><div className="section-heading"><div><span className="eyebrow"><span className="eyebrow-line"/> HOW CAN WE HELP?</span><h2>Beyond the <em>phone.</em></h2></div><Link href="/services" className="text-link">All services <ArrowUpRight size={17}/></Link></div><div className="services-grid"><Link href="/services" className="service-card"><div className="service-number">01 / REPAIR</div><div className="service-icon"><Smartphone size={35}/></div><h3>Phone<br/>Repairs.</h3><p>Help with screen, battery and device concerns.</p><span className="service-arrow"><ArrowUpRight size={20}/></span></Link><Link href="/services" className="service-card service-card-accent"><div className="service-number">02 / CUSTOMISE</div><div className="service-icon"><PenTool size={35}/></div><h3>Make it<br/>your own.</h3><p>Add a personal touch to your everyday device.</p><span className="service-arrow"><ArrowUpRight size={20}/></span></Link><Link href="/services" className="service-card service-card-dark"><div className="service-number">03 / UPGRADE</div><div className="service-icon"><Sparkles size={35}/></div><h3>Time for<br/>an Upgrade?</h3><p>Explore iPhones that suit your budget and needs.</p><span className="service-arrow"><ArrowUpRight size={20}/></span></Link></div></section>
<section className="cta-section container"><div className="cta-panel"><div><span className="eyebrow">LET'S TALK MOBILE</span><h2>Ready for<br/><em>what’s next?</em></h2><p>Have a question about an iPhone or a repair? We’re here to help you explore your options.</p><Link href="/contact" className="btn btn-white">Get in touch <ArrowUpRight size={18}/></Link></div><div className="cta-decoration">C<span>✳</span></div></div></section></main>
}
