export type Product = {id:string;name:string;subtitle:string;price:number;oldPrice?:number;category:'iPhone'|'Android'|'Accessories';color:string;finish:string;storage:string;badge?:string;isNew?:boolean;description:string;features:string[]};
export const products:Product[] = [
{id:'iphone-16-pro-max',name:'iPhone 16 Pro Max',subtitle:'The ultimate iPhone experience.',price:389900,oldPrice:415000,category:'iPhone',color:'#a8a39a',finish:'Desert Titanium',storage:'256GB',badge:'BEST SELLER',description:'A flagship experience with a stunning display, powerful performance and a refined titanium finish.',features:['6.9-inch Super Retina XDR display','Pro camera system','Titanium design','USB-C connectivity']},
{id:'iphone-16-pro',name:'iPhone 16 Pro',subtitle:'Pro power. Perfectly sized.',price:329900,category:'iPhone',color:'#b6b4ae',finish:'Natural Titanium',storage:'128GB',badge:'POPULAR',description:'A beautifully capable iPhone built for creators and everyday power users.',features:['6.3-inch Super Retina XDR display','Pro camera system','Titanium design','USB-C connectivity']},
{id:'iphone-16',name:'iPhone 16',subtitle:'A new kind of everyday magic.',price:249900,oldPrice:269900,category:'iPhone',color:'#b6b1d8',finish:'Ultramarine',storage:'128GB',badge:'GREAT VALUE',description:'The perfect balance of performance, photography and personality.',features:['6.1-inch Super Retina XDR display','Advanced dual-camera system','All-day battery life','USB-C connectivity']},
{id:'iphone-15-pro-max',name:'iPhone 15 Pro Max',subtitle:'Still exceptionally Pro.',price:289900,category:'iPhone',color:'#929591',finish:'Natural Titanium',storage:'256GB',description:'An impressive Pro iPhone with premium performance and iconic design.',features:['6.7-inch Super Retina XDR display','Pro camera system','Titanium design','USB-C connectivity']},
{id:'iphone-15',name:'iPhone 15',subtitle:'Classic. Powerful. Loved.',price:199900,oldPrice:215000,category:'iPhone',color:'#c7d5c6',finish:'Green',storage:'128GB',badge:'HOT DEAL',description:'A brilliant everyday iPhone with Dynamic Island and great camera performance.',features:['6.1-inch Super Retina XDR display','Dynamic Island','48MP main camera','USB-C connectivity']},
{id:'iphone-14',name:'iPhone 14',subtitle:'Everything you need.',price:159900,category:'iPhone',color:'#d6d5e8',finish:'Purple',storage:'128GB',description:'A beloved iPhone with reliable performance and a stylish finish.',features:['6.1-inch Super Retina XDR display','Dual-camera system','Face ID','Lightning connectivity']},
{id:'galaxy-s24',name:'Galaxy S24 Ultra',subtitle:'Power for every possibility.',price:319900,category:'Android',color:'#888782',finish:'Titanium Gray',storage:'256GB',description:'An ultra-premium Android experience made for productivity and creativity.',features:['Large AMOLED display','Multi-lens camera system','S Pen support','Fast performance']},
{id:'pixel-9',name:'Google Pixel 9',subtitle:'Smart by design.',price:219900,category:'Android',color:'#b8c4b8',finish:'Wintergreen',storage:'128GB',description:'Thoughtful Android design with intelligent photography features.',features:['OLED display','Computational photography','Clean Android experience','USB-C connectivity']},
{id:'airpods-pro',name:'AirPods Pro',subtitle:'Lose yourself in the sound.',price:64900,category:'Accessories',color:'#e5e5e2',finish:'White',storage:'2nd Gen',badge:'FAVORITE',description:'Immersive wireless listening with a comfortable and compact design.',features:['Active Noise Cancellation','Transparency mode','Wireless charging case','Seamless pairing']},
{id:'magsafe',name:'MagSafe Charger',subtitle:'Snap on. Power up.',price:14900,category:'Accessories',color:'#e6e6e5',finish:'White',storage:'1m Cable',description:'A convenient magnetic wireless charging accessory.',features:['Magnetic alignment','Wireless charging','Compact design','USB-C connection']}
];
export const money=(n:number)=>'Rs. '+n.toLocaleString('en-LK');
export const services=[{id:'repair',title:'Expert phone repairs',description:'From screens and batteries to charging issues, get a clear assessment from our team.',icon:'wrench'},{id:'custom',title:'Customisation & upgrades',description:'Give your phone a fresh look with select cosmetic modifications and upgrades.',icon:'sparkles'},{id:'trade',title:'Upgrade guidance',description:'Explore the right iPhone for your needs, preferences and budget.',icon:'repeat'}];
